language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "nightly" # CPython latest
install:
  - "pip install -r requirements.txt"
  - "mkdir -p .doccu/static/js"
  - "mkdir -p .doccu/static/img"
  - "mkdir -p .doccu/documents"
  - "git clone https://github.com/shakna-israel/doccu-templates .doccu/templates"
  - "python travis-setup.py"
script: "nosetests"
