language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.2"
 - "3.4"
 - "pypy"
 - "pypy3"
 - "nightly" # CPython latest
install:
  - "pip install -r requirements.txt"
  - "mkdir .doccu"
  - "git clone https://github.com/shakna-israel/doccu-templates .doccu/templates"
  - "python travis-static.py"
script: "nosetests"
